import { PlatformAdminUser } from '@packages/domain-platform-admin';

export interface PlatformAdminMfaSetupVerifyInput {
  setupToken: string; // expected format: `mfa_setup_{adminId}`
  code: string; // 6-digit TOTP code
}

export interface PlatformAdminMfaSetupVerifyResult {
  adminId: string;
}

/**
 * Step 2 of MFA enrollment: confirm the TOTP code generated by the user's
 * Authenticator app and mark the admin as enrolled. The pending secret must
 * already be persisted (written during setup step 1).
 */
export class PlatformAdminMfaSetupVerify {
  public constructor(
    private readonly adminById: (id: string) => Promise<PlatformAdminUser | null>,
    private readonly verifyTotp: (secret: string | null, code: string) => Promise<boolean>,
    private readonly enrollMfa: (id: string, secret: string) => Promise<void>,
  ) {}

  public async execute(
    input: PlatformAdminMfaSetupVerifyInput,
  ): Promise<PlatformAdminMfaSetupVerifyResult> {
    const adminId = input.setupToken.replace('mfa_setup_', '');
    if (!adminId) throw new Error('Invalid setup token');

    const admin = await this.adminById(adminId);
    if (!admin) throw new Error('Platform admin not found');

    if (!admin.isActive || admin.isLockedOut()) throw new Error('Platform admin account locked');

    const ok = await this.verifyTotp(admin.mfaSecret, input.code);
    if (!ok) {
      throw new Error('Invalid MFA code');
    }

    await this.enrollMfa(adminId, admin.mfaSecret ?? '');
    return { adminId };
  }
}
