import { z } from 'zod';
import { DiscountType } from '@packages/domain-promotions';

export const CreateDiscountRuleSchema = z.object({
  name: z.string().min(1),
  type: z.enum(['item', 'cart', 'category', 'customer', 'membership', 'time_based', 'buy_x_get_y', 'quantity_break']),
  ruleJson: z.object({
    type: z.enum(['item', 'cart', 'category', 'customer', 'membership', 'time_based', 'buy_x_get_y', 'quantity_break']),
    discountType: z.enum(['percentage', 'fixed']),
    amount: z.number().int().positive(),
    productIds: z.array(z.string()).optional(),
    minimumTotal: z.number().int().nonnegative().optional(),
    categoryIds: z.array(z.string()).optional(),
    customerIds: z.array(z.string()).optional(),
    tierIds: z.array(z.string()).optional(),
    membershipLevel: z.string().optional(),
    dayOfWeek: z.array(z.number().int().min(0).max(6)).optional(),
    timeRange: z.object({ start: z.string(), end: z.string() }).optional(),
    validFrom: z.string().optional(),
    validTo: z.string().optional(),
    buyProductId: z.string().optional(),
    buyQuantity: z.number().int().positive().optional(),
    getProductId: z.string().optional(),
    getQuantity: z.number().int().positive().optional(),
    getDiscountPercent: z.number().int().min(1).max(100).optional(),
    quantityProductId: z.string().optional(),
    tiers: z.array(z.object({ minQuantity: z.number().int().positive(), discountPercent: z.number().int().min(1).max(100) })).default([]),
  }),
  validFrom: z.string().optional(),
  validUntil: z.string().optional(),
  priority: z.number().int().nonnegative().default(0),
  isExclusive: z.boolean().default(false),
});

export const UpdateDiscountRuleSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1).optional(),
  ruleJson: z.object({
    type: z.enum(['item', 'cart', 'category', 'customer', 'membership', 'time_based', 'buy_x_get_y', 'quantity_break']).optional(),
    discountType: z.enum(['percentage', 'fixed']).optional(),
    amount: z.number().int().positive().optional(),
    productIds: z.array(z.string()).optional(),
    minimumTotal: z.number().int().nonnegative().optional(),
    categoryIds: z.array(z.string()).optional(),
    customerIds: z.array(z.string()).optional(),
    tierIds: z.array(z.string()).optional(),
    membershipLevel: z.string().optional(),
    dayOfWeek: z.array(z.number().int().min(0).max(6)).optional(),
    timeRange: z.object({ start: z.string(), end: z.string() }).optional(),
    validFrom: z.string().optional(),
    validTo: z.string().optional(),
    buyProductId: z.string().optional(),
    buyQuantity: z.number().int().positive().optional(),
    getProductId: z.string().optional(),
    getQuantity: z.number().int().positive().optional(),
    getDiscountPercent: z.number().int().min(1).max(100).optional(),
    quantityProductId: z.string().optional(),
    tiers: z.array(z.object({ minQuantity: z.number().int().positive(), discountPercent: z.number().int().min(1).max(100) })).optional(),
  }).optional(),
  priority: z.number().int().nonnegative().optional(),
  isExclusive: z.boolean().optional(),
});
