export const ALL_PERMISSION_CODES = [
  'company.view',
  'company.edit',
  'branch.view',
  'branch.create',
  'branch.edit',
  'branch.archive',
  'warehouse.view',
  'warehouse.create',
  'warehouse.edit',
  'users.view',
  'users.create',
  'users.edit',
  'users.deactivate',
  'roles.view',
  'roles.create_custom',
  'roles.edit',
  'roles.assign',
  'permissions.view_matrix',
  'shift.configure_hours',
  'approval_workflow.configure',
  'catalog.view',
  'catalog.create',
  'catalog.edit',
  'catalog.delete',
  'catalog.price.edit',
  'catalog.barcode.generate',
  'catalog.bundle.configure',
  'catalog.unit_conversion.edit',
  'inventory.view',
  'inventory.adjust',
  'inventory.adjust.approve',
  'inventory.batch.manage',
  'inventory.transfer.create',
  'inventory.transfer.approve',
  'inventory.transfer.receive',
  'sales.create',
  'sales.view',
  'sales.discount.apply',
  'sales.discount.approve',
  'sales.void',
  'sales.refund.approve',
  'sales.return.create',
  'sales.cash_drawer.open_no_sale',
  'sales.shift.open_close',
  'sales.shift.reconciliation.view',
  'purchasing.supplier.view',
  'purchasing.supplier.manage',
  'purchasing.po.create',
  'purchasing.po.approve',
  'purchasing.po.receive',
  'purchasing.invoice.record',
  'purchasing.invoice.ocr_import',
  'customers.view',
  'customers.create',
  'customers.edit',
  'customers.credit.manage',
  'customers.loyalty.redeem',
  'customers.loyalty.configure',
  'payments.tender.record',
  'payments.provider.configure',
  'promotions.discount.create',
  'promotions.coupon.create',
  'promotions.campaign.manage',
  'promotions.view',
  'tax.rules.view',
  'tax.rules.edit',
  'tax.eta.activate_module',
  'tax.eta.submit_invoice',
  'tax.eta.view_status',
  'warehouse.central.designate',
  'warehouse.reorder_point.edit',
  'warehouse.reorder_point.accept_ai_suggestion',
  'reports.view.sales',
  'reports.view.financial',
  'reports.view.inventory',
  'reports.view.employees',
  'reports.view.customers',
  'reports.view.purchasing',
  'reports.branch_comparison.view',
  'reports.export',
  'reports.schedule_delivery',
  'notifications.preferences.edit_own',
  'notifications.preferences.edit_others',
  'notifications.billing_trial.view',
  'ai.assistant.use',
  'ai.predictions.view',
  'ai.recommendation.accept_reject',
  'ai.fraud_alerts.view',
  'ai.health_score.view',
  'ai.ocr.use',
  'ai.insight_feedback.submit',
  'sync.status.view',
  'sync.conflicts.view',
  'sync.conflicts.resolve',
  'sync.conflicts.resolve.security_sensitive',
  'sync.device.register',
  'sync.device.revoke',
  'audit.view',
  'security.session.manage_own',
  'security.session.revoke_others',
  'security.encryption_status.view',
  'settings.company.edit',
  'settings.branch.edit',
  'settings.hardware.configure',
  'settings.localization.edit',
  'devices.view',
  'devices.manage',
  'backup.trigger_manual',
  'backup.configure_schedule',
  'backup.restore',
  'backup.view_history',
  'subscription.view',
  'subscription.upgrade',
  'subscription.billing_history.view',
  'data.export.reports',
  'data.export.catalog',
  'data.export.customers',
  'data.import.catalog',
  'platform.accounts.view',
  'platform.accounts.plan.change',
  'platform.accounts.override.grant',
  'platform.accounts.suspend',
  'platform.accounts.reactivate',
  'platform.accounts.trial.extend',
  'platform.audit.view',
  'platform.admins.manage',
] as const;

type PermissionMatrixValue = readonly PermissionCode[];

export const SYSTEM_ROLE_PERMISSION_MATRIX: Record<string, PermissionMatrixValue> = {
  Owner: [...ALL_PERMISSION_CODES],
  'Company Administrator': [
    'company.view',
    'company.edit',
    'branch.view',
    'branch.create',
    'branch.edit',
    'warehouse.view',
    'warehouse.create',
    'warehouse.edit',
    'users.view',
    'users.create',
    'users.edit',
    'roles.view',
    'roles.assign',
    'catalog.view',
    'catalog.create',
    'catalog.edit',
    'inventory.view',
    'inventory.adjust',
    'inventory.batch.manage',
    'sales.create',
    'sales.view',
    'sales.discount.apply',
    'purchasing.po.create',
    'purchasing.po.approve',
    'customers.view',
    'customers.create',
    'customers.edit',
    'reports.view.sales',
    'reports.view.financial',
    'reports.view.inventory',
    'sync.status.view',
    'audit.view',
    'settings.company.edit',
    'settings.branch.edit',
    'subscription.view',
    'backup.view_history',
    'backup.restore',
  ],
  'Branch Manager': [
    'branch.view',
    'warehouse.view',
    'inventory.view',
    'inventory.adjust',
    'sales.create',
    'sales.view',
    'sales.discount.apply',
    'users.view',
    'roles.view',
    'catalog.view',
    'reports.view.sales',
    'reports.view.inventory',
    'sync.status.view',
    'customers.view',
    'customers.create',
    'customers.edit',
    'subscription.view',
  ],
  'Assistant Manager': [
    'inventory.view',
    'inventory.adjust',
    'sales.create',
    'sales.view',
    'sales.discount.apply',
    'customers.view',
    'reports.view.sales',
    'sync.status.view',
    'subscription.view',
  ],
  Cashier: [
    'sales.create',
    'sales.view',
    'customers.view',
    'customers.create',
    'payments.tender.record',
    'subscription.view',
  ],
  'Inventory Manager': [
    'inventory.view',
    'inventory.adjust',
    'catalog.view',
    'catalog.edit',
    'warehouse.view',
    'reports.view.inventory',
    'sync.status.view',
    'subscription.view',
  ],
  'Warehouse Employee': [
    'warehouse.view',
    'inventory.view',
    'inventory.adjust',
    'sync.status.view',
  ],
  'Purchasing Officer': [
    'purchasing.po.create',
    'purchasing.po.approve',
    'purchasing.supplier.view',
    'inventory.view',
    'reports.view.purchasing',
    'subscription.view',
  ],
  'Sales Employee': ['sales.create', 'sales.view', 'customers.view', 'payments.tender.record'],
  Accountant: ['reports.view.financial', 'subscription.view', 'sales.view', 'customers.view'],
  'Financial Manager': [
    'reports.view.financial',
    'reports.export',
    'subscription.view',
    'sales.view',
    'customers.view',
  ],
  Auditor: ['audit.view', 'reports.view.financial', 'reports.view.sales', 'reports.view.inventory'],
  'Customer Service': ['customers.view', 'customers.create', 'customers.edit', 'sales.view'],
  'Marketing Employee': ['customers.view', 'customers.loyalty.redeem', 'promotions.view'],
  'Delivery Employee': ['sales.view', 'customers.view', 'warehouse.view'],
  'Technical Support': [
    'devices.view',
    'devices.manage',
    'security.encryption_status.view',
    'sync.status.view',
  ],
  'Read-only User': [
    'catalog.view',
    'inventory.view',
    'sales.view',
    'customers.view',
    'reports.view.sales',
    'reports.view.financial',
    'reports.view.inventory',
    'subscription.view',
    'sync.status.view',
    'audit.view',
  ],
} as const;

export type SystemRoleName = keyof typeof SYSTEM_ROLE_PERMISSION_MATRIX;
export type PermissionCode = (typeof ALL_PERMISSION_CODES)[number];

export function canAccessPermission(roleName: string, permissionCode: string): boolean {
  const normalizedRole = roleName as SystemRoleName;
  const permissions = SYSTEM_ROLE_PERMISSION_MATRIX[normalizedRole];
  if (!permissions) {
    return false;
  }

  return permissions.some((code: PermissionCode) => code === (permissionCode as PermissionCode));
}
